In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_excel('/content/drive/MyDrive/nlp pj/unsmile_train_v1.0.xlsx', engine = "openpyxl")

In [4]:
df

,문장,여성/가족,남성,성소수자,인종/국적,연령,지역,종교,기타 혐오,악플/욕설,clean,개인지칭
0,일안하는 시간은 쉬고싶어서 그런게 아닐까,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,아동성범죄와 페도버는 기록바 끊어져 영원히 고통 받는다. 무슬림 50퍼 근친이다. ...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,루나 솔로앨범 나왔을 때부터 머모 기운 있었음 ㅇㅇ Keep o doin 진짜 띵...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,홍팍에도 어버이연합인가 보내요 뭐 이런뎃글 있는데 이거 어버이연합측에 신고하면 그쪽...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,아놔 왜 여기 댓들은 다 여자들이 김치녀라고 먼저 불렸다! 여자들은 더 심하게 그런...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
15000,께롱께롱께롱!!!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15001,갱상도가아니라 홍어지 개좃같은 홍어년들,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
15002,말레이시아랑 인도네시아 여자 존나 못생겼던데,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15003,링크도 안박고 가서 글 쓰자고 선동하네,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15004,"멸치가 틀딱 짜증나서 트러블나면 조직적으로 좀스럽게 보복함ex: 수건찜유도탄, 틀한...",0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

폭력적 데이터 고르기

In [5]:
# 폭력적인 내용일 경우 '여성/가족', '남성', '성소수자', '인종/국적', '연령', '지역', '종교', '기타 혐오', '악플/욕설'의 값의 합이 1이상일 것이다
# 개인지칭의 경우 문제가 될 소지가 있기때문에 함께 넣었습니다.

In [6]:
df_v = df[['여성/가족', '남성', '성소수자', '인종/국적', '연령', '지역', '종교', '기타 혐오', '악플/욕설', '개인지칭']]

In [7]:
df_v['total'] = df_v.sum(axis=1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [8]:
df_v

       여성/가족   남성  성소수자  인종/국적   연령   지역   종교  기타 혐오  악플/욕설  개인지칭  total
0        0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
1        0.0  0.0   0.0    0.0  0.0  0.0  1.0    0.0    0.0   0.0    1.0
2        0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
3        0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
4        1.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    1.0
...      ...  ...   ...    ...  ...  ...  ...    ...    ...   ...    ...
15000    0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
15001    0.0  0.0   0.0    0.0  0.0  1.0  0.0    0.0    0.0   0.0    1.0
15002    1.0  0.0   0.0    1.0  0.0  0.0  0.0    0.0    0.0   0.0    2.0
15003    0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    1.0   0.0    1.0
15004    0.0  0.0   0.0    0.0  1.0  0.0  0.0    0.0    0.0   0.0    1.0

[15005 rows x 11 columns]

astype을 통해 0과 1로 데이터의 값을 변경했습니다.

In [9]:
df_v['total'] = df_v['total'].astype(bool).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
df_v

       여성/가족   남성  성소수자  인종/국적   연령   지역   종교  기타 혐오  악플/욕설  개인지칭  total
0        0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
1        0.0  0.0   0.0    0.0  0.0  0.0  1.0    0.0    0.0   0.0    1.0
2        0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
3        0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
4        1.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    1.0
...      ...  ...   ...    ...  ...  ...  ...    ...    ...   ...    ...
15000    0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    0.0   0.0    0.0
15001    0.0  0.0   0.0    0.0  0.0  1.0  0.0    0.0    0.0   0.0    1.0
15002    1.0  0.0   0.0    1.0  0.0  0.0  0.0    0.0    0.0   0.0    1.0
15003    0.0  0.0   0.0    0.0  0.0  0.0  0.0    0.0    1.0   0.0    1.0
15004    0.0  0.0   0.0    0.0  1.0  0.0  0.0    0.0    0.0   0.0    1.0

[15005 rows x 11 columns]

In [11]:
df['violence'] = df_v['total']

In [12]:
df

,문장,여성/가족,남성,성소수자,인종/국적,연령,지역,종교,기타 혐오,악플/욕설,clean,개인지칭,violence
0,일안하는 시간은 쉬고싶어서 그런게 아닐까,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,아동성범죄와 페도버는 기록바 끊어져 영원히 고통 받는다. 무슬림 50퍼 근친이다. ...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,루나 솔로앨범 나왔을 때부터 머모 기운 있었음 ㅇㅇ Keep o doin 진짜 띵...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,홍팍에도 어버이연합인가 보내요 뭐 이런뎃글 있는데 이거 어버이연합측에 신고하면 그쪽...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,아놔 왜 여기 댓들은 다 여자들이 김치녀라고 먼저 불렸다! 여자들은 더 심하게 그런...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15000,께롱께롱께롱!!!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15001,갱상도가아니라 홍어지 개좃같은 홍어년들,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
15002,말레이시아랑 인도네시아 여자 존나 못생겼던데,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15003,링크도 안박고 가서 글 쓰자고 선동하네,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
15004,"멸치가 틀딱 짜증나서 트러블나면 조직적으로 좀스럽게 보복함ex: 수건찜유도탄, 틀한...",0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

필요없는 컬럼 삭제

In [13]:
df.drop('개인지칭',axis=1, inplace=True)
df.drop('악플/욕설',axis=1, inplace=True)
df.drop('기타 혐오',axis=1, inplace=True)
df.drop('종교',axis=1, inplace=True)
df.drop('지역',axis=1, inplace=True)
df.drop('연령',axis=1, inplace=True)
df.drop('인종/국적',axis=1, inplace=True)
df.drop('성소수자',axis=1, inplace=True)
df.drop('남성',axis=1, inplace=True)
df.drop('여성/가족',axis=1, inplace=True)

In [14]:
df

                                                      문장  clean  violence
0                                 일안하는 시간은 쉬고싶어서 그런게 아닐까    1.0       0.0
1      아동성범죄와 페도버는 기록바 끊어져 영원히 고통 받는다. 무슬림 50퍼 근친이다. ...    0.0       1.0
2      루나 솔로앨범 나왔을 때부터 머모 기운 있었음 ㅇㅇ Keep o  doin 진짜 띵...    1.0       0.0
3      홍팍에도 어버이연합인가 보내요 뭐 이런뎃글 있는데 이거 어버이연합측에 신고하면 그쪽...    1.0       0.0
4      아놔 왜 여기 댓들은 다 여자들이 김치녀라고 먼저 불렸다! 여자들은 더 심하게 그런...    0.0       1.0
...                                                  ...    ...       ...
15000                                          께롱께롱께롱!!!    1.0       0.0
15001                              갱상도가아니라 홍어지 개좃같은 홍어년들    0.0       1.0
15002                           말레이시아랑 인도네시아 여자 존나 못생겼던데    0.0       1.0
15003                              링크도 안박고 가서 글 쓰자고 선동하네    0.0       1.0
15004  멸치가 틀딱 짜증나서 트러블나면 조직적으로 좀스럽게 보복함ex: 수건찜유도탄, 틀한...    0.0       1.0

[15005 rows x 3 columns]

In [15]:
condition = (df.violence == 0) & (df.clean == 0)
df_spy = df[condition]

In [16]:
df_spy

                                                      문장  clean  violence
5876   혹시 돼지한명이랑 멸치 두명 무리 아니노 ㅋ 노천탕에서 자주봄 거기 사장들 달로 끊...    0.0       0.0
11942  누가 대통령이 지나가다가 여자 하나 성폭행했다고 고발해도 안했다는 증거 없으니 잡아...    0.0       0.0

이상한 값을 가진 행을 처리해줍니다.

In [17]:
df.loc[5876, 'violence'] = 1
df.loc[11942, 'clean'] = 1

In [18]:
condition = (df.violence == 0) & (df.clean == 0)
df_spy1 = df[condition]

In [19]:
df_spy1

Empty DataFrame
Columns: [문장, clean, violence]
Index: []

In [20]:
df.to_csv("unsmile_fin.csv", index=False, encoding="utf-8-sig")